name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/docker-image.yml
      - Dockerfile
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/docker-image.yml
      - Dockerfile

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: irhythm/sodavalidator
      IMAGE_TAG: latest_$(RELEASE)
      BRANCH: $(git rev-parse --symbolic --abbrev-ref HEAD)
      DATE: $(date +%s)
      RELEASE: $(git tag --sort=committerdate | tail -1)
      
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag $IMAGE_NAME:latest_$(git rev-parse --symbolic --abbrev-ref HEAD)_$(git tag --sort=committerdate | tail -1)
